###
POST http://localhost:3333/subscriptions
Content-Type: application/json  

{
    "name": "Amigo23 ",
    "email": "amigo23@gmail.com",
    "referrer": "df3c077e-3ffd-4907-af94-9719fca75cd5"

}
###

GET http://localhost:3333/invites/df3c077e-3ffd-4907-af94-9719fca75cd5

###

GET http://localhost:3333/subscribers/df3c077e-3ffd-4907-af94-9719fca75cd5/ranking/clicks

###

GET http://localhost:3333/subscribers/df3c077e-3ffd-4907-af94-9719fca75cd5/ranking/count

###

GET http://localhost:3333/subscribers/df3c077e-3ffd-4907-af94-9719fca75cd5/ranking/position

###

GET http://localhost:3333/ranking

###



